import logging
from typing import Optional, Dict, Any
from integrations.confluence_client import ConfluenceClient
import re

log = logging.getLogger(__name__)


class ConfluencePublisher:
    def __init__(self):
        self.client = ConfluenceClient()

    def _convert_markdown_to_confluence_storage(self, markdown_text: str) -> str:
        html = markdown_text
        html = re.sub(r"^## (.*?)$", r"<h2>\1</h2>", html, flags=re.MULTILINE)
        html = re.sub(r"^### (.*?)$", r"<h3>\1</h3>", html, flags=re.MULTILINE)
        html = re.sub(r"^\*\*([^*]+)\*\*", r"<strong>\1</strong>", html, flags=re.MULTILINE)
        html = re.sub(r"_([^_]+)_", r"<i>\1</i>", html)
        html = re.sub(r"^- (.+)$", r"<li>\1</li>", html, flags=re.MULTILINE)

        li_blocks = re.findall(r"(<li>.*?</li>)", html, re.DOTALL)
        if li_blocks:
            combined = "<ul>" + "".join(li_blocks) + "</ul>"
            html = re.sub(r"(<li>.*?</li>)+", combined, html, flags=re.DOTALL)

        html = html.replace("\n", "<br/>")
        return html

    def _build_confluence_body(self, doc_dict: Dict[str, Any]) -> str:
        sections = doc_dict.get("sections", {})
        body_html = "<div class='dreamfi-document'>"

        generator_type = doc_dict.get("generator_type", "")
        body_html += f"<p><em>Generated by: {generator_type}</em></p>"

        for section_name, content in sections.items():
            body_html += f"<h3>{section_name}</h3>"
            converted = self._convert_markdown_to_confluence_storage(str(content))
            body_html += f"<div class='section'>{converted}</div>"

        body_html += "</div>"
        return body_html

    def publish_page(
        self,
        doc_dict: Dict[str, Any],
        space_key: str,
        parent_page_id: Optional[str] = None,
        update_if_exists: bool = True
    ) -> Dict[str, Any]:
        title = doc_dict.get("title", "Untitled Document")
        body_html = self._build_confluence_body(doc_dict)

        try:
            if update_if_exists:
                existing = self._find_page_by_title(space_key, title)
                if existing:
                    result = self.client.update_page(
                        page_id=existing["id"],
                        title=title,
                        body_html=body_html
                    )
                    log.info(f"Updated page {title} ({existing['id']})")
                    return {
                        "success": True,
                        "page_id": existing["id"],
                        "url": existing.get("_links", {}).get("webui", ""),
                        "action": "updated"
                    }

            result = self.client.create_page(
                space_key=space_key,
                title=title,
                body_html=body_html,
                parent_id=parent_page_id
            )

            page_id = result.get("id")
            web_url = f"{self.client._confluence.url}/wiki/spaces/{space_key}/pages/{page_id}"

            log.info(f"Created page {title} ({page_id})")
            return {
                "success": True,
                "page_id": page_id,
                "url": web_url,
                "action": "created"
            }

        except Exception as e:
            log.error(f"Failed to publish page: {e}")
            return {
                "success": False,
                "error": str(e),
                "action": "failed"
            }

    def _find_page_by_title(self, space_key: str, title: str) -> Optional[Dict[str, Any]]:
        try:
            cql = f'space = {space_key} AND title ~ "{title}"'
            results = self.client._confluence.cql(cql=cql, limit=1)
            if results.get("results"):
                return results["results"][0]
            return None
        except Exception as e:
            log.debug(f"Could not search for existing page: {e}")
            return None

    def publish_batch(
        self,
        doc_dicts: list[Dict[str, Any]],
        space_key: str,
        parent_page_id: Optional[str] = None
    ) -> list[Dict[str, Any]]:
        results = []
        for doc in doc_dicts:
            result = self.publish_page(doc, space_key, parent_page_id)
            results.append(result)
        return results

    def link_pages(self, source_page_id: str, target_page_id: str, link_type: str = "relates to") -> bool:
        try:
            self.client._confluence.create_page_link(
                source_page_id=source_page_id,
                target_page_id=target_page_id,
                link_type=link_type
            )
            log.info(f"Linked pages: {source_page_id} -> {target_page_id}")
            return True
        except Exception as e:
            log.error(f"Failed to link pages: {e}")
            return False
