import type { ConsolePayload } from '../types/console'

const now = '2026-04-21T14:30:00Z'
const onyxNativeSetup = {
  connection_method: 'onyx_native' as const,
  setup_method: 'Onyx native connector',
  setup_detail: 'Configure credentials in Onyx, then let DreamFi validate the document set and freshness.',
  requires_dreamfi_secret: false,
  config_schema: [],
}
const customIngestionSetup = {
  connection_method: 'custom_ingestion' as const,
  setup_method: 'Custom/export ingestion',
  setup_detail: 'Ingest through an Onyx File/Web/S3 source or a DreamFi source bridge.',
  requires_dreamfi_secret: true,
  config_schema: [],
}

export const consoleDevelopmentSlice: ConsolePayload = {
  headline: 'Development source-room slice',
  summary: {
    skill_count: 9,
    active_prompt_count: 9,
    average_latest_score: 0.884,
    average_confidence: 0.861,
    average_export_readiness: 0.902,
    publish_success_rate: 0.8,
    hard_gate_pass_rate: 0.875,
    blocked_artifact_count: 1,
    publish_ready_count: 3,
    published_artifact_count: 5,
    needs_review_count: 1,
  },
  skills: [
    {
      skill_id: 'technical_prd',
      display_name: 'Technical PRD',
      description: 'Turns sourced product and engineering context into a technical PRD.',
      criteria_count: 7,
      active_prompt_version: 3,
      latest_round: {
        round_id: 'dev-round-technical-prd',
        prompt_version_id: 'dev-prompt-technical-prd-v3',
        score: 0.91,
        previous_score: 0.86,
        improvement: 0.05,
        completed_at: now,
        artifacts_path: 'dev/artifacts/technical-prd',
      },
      recent_rounds: [],
    },
  ],
  artifact_queue: [
    {
      output_id: 'dev-artifact-kyc-drop',
      skill_id: 'technical_prd',
      skill_display_name: 'Technical PRD',
      round_id: 'dev-round-technical-prd',
      test_input_label: 'KYC conversion drop investigation',
      attempt: 1,
      pass_fail: 'pass',
      confidence: 0.89,
      export_readiness: 0.92,
      created_at: now,
      status: 'publish_ready',
      artifacts_path: 'dev/artifacts/technical-prd/kyc-drop',
      latest_publish: null,
    },
    {
      output_id: 'dev-artifact-risk-brd',
      skill_id: 'risk_brd',
      skill_display_name: 'Risk BRD',
      round_id: 'dev-round-risk-brd',
      test_input_label: 'Socure retry policy review',
      attempt: 1,
      pass_fail: 'pass',
      confidence: 0.84,
      export_readiness: 0.79,
      created_at: '2026-04-21T13:10:00Z',
      status: 'needs_review',
      artifacts_path: 'dev/artifacts/risk-brd/socure-retry',
      latest_publish: null,
    },
  ],
  publish_activity: [
    {
      publish_id: 'dev-publish-weekly-brief',
      skill_id: 'weekly_brief',
      destination: 'confluence',
      destination_ref: 'Product Weekly Brief',
      decision: 'published',
      reason: null,
      created_at: '2026-04-21T12:45:00Z',
    },
  ],
  alerts: [
    {
      id: 'dev-needs-review',
      severity: 'warning',
      title: 'One development artifact needs review',
      message: 'The Socure retry policy BRD is below publish-ready threshold.',
      href: '/console/review?focus=dev-artifact-risk-brd',
      created_at: '2026-04-21T13:10:00Z',
    },
  ],
  quick_actions: [
    {
      id: 'weekly-brief',
      label: 'Run weekly PM brief',
      href: '/console/generate/weekly-brief',
      kind: 'primary',
    },
    {
      id: 'technical-prd',
      label: 'Create Technical PRD',
      href: '/console/generate/technical-prd',
      kind: 'secondary',
    },
    {
      id: 'business-prd',
      label: 'Create Business PRD',
      href: '/console/generate/business-prd',
      kind: 'secondary',
    },
    {
      id: 'risk-brd',
      label: 'Create Risk BRD',
      href: '/console/generate/risk-brd',
      kind: 'secondary',
    },
    {
      id: 'review-blocked',
      label: 'Review blocked artifacts',
      href: '/console/review?status=blocked',
      kind: 'secondary',
    },
    {
      id: 'trust-dashboard',
      label: 'Open trust dashboard',
      href: '/console/trust',
      kind: 'secondary',
    },
  ],
  integrations: [
    {
      id: 'jira',
      name: 'Jira',
      category: 'planning',
      purpose: 'Sprints, issues, and delivery state for product investigation.',
      used_for: ['weekly-brief', 'technical-prd', 'risk-brd'],
      status: 'connected',
      href: '/console/integrations/jira',
      ...onyxNativeSetup,
    },
    {
      id: 'dragonboat',
      name: 'Dragonboat',
      category: 'planning',
      purpose: 'Roadmap, initiative, and OKR alignment context.',
      used_for: ['weekly-brief', 'business-prd'],
      status: 'available',
      href: '/console/integrations/dragonboat',
      ...customIngestionSetup,
    },
    {
      id: 'confluence',
      name: 'Confluence',
      category: 'docs',
      purpose: 'Specs, PRDs, decisions, and publish destinations.',
      used_for: ['weekly-brief', 'technical-prd', 'business-prd', 'risk-brd'],
      status: 'connected',
      href: '/console/integrations/confluence',
      ...onyxNativeSetup,
    },
    {
      id: 'metabase',
      name: 'Metabase',
      category: 'metrics',
      purpose: 'SQL-backed KPI and funnel dashboards.',
      used_for: ['weekly-brief', 'business-prd'],
      status: 'connected',
      href: '/console/integrations/metabase',
      ...customIngestionSetup,
    },
    {
      id: 'posthog',
      name: 'PostHog',
      category: 'product_analytics',
      purpose: 'Product events, funnels, cohorts, and session context.',
      used_for: ['weekly-brief', 'technical-prd'],
      status: 'connected',
      href: '/console/integrations/posthog',
      ...customIngestionSetup,
    },
    {
      id: 'ga',
      name: 'Google Analytics',
      category: 'marketing_analytics',
      purpose: 'Acquisition, traffic, and conversion signal context.',
      used_for: ['business-prd'],
      status: 'available',
      href: '/console/integrations/ga',
      ...customIngestionSetup,
    },
    {
      id: 'klaviyo',
      name: 'Klaviyo',
      category: 'marketing',
      purpose: 'Lifecycle messaging, audiences, and campaign sends.',
      used_for: ['business-prd'],
      status: 'available',
      href: '/console/integrations/klaviyo',
      ...customIngestionSetup,
    },
    {
      id: 'netxd',
      name: 'NetXD',
      category: 'payments',
      purpose: 'Payment and ledger transaction context.',
      used_for: ['technical-prd', 'risk-brd'],
      status: 'connected',
      href: '/console/integrations/netxd',
      ...customIngestionSetup,
    },
    {
      id: 'sardine',
      name: 'Sardine',
      category: 'risk',
      purpose: 'Fraud and risk decision signal enrichment.',
      used_for: ['risk-brd'],
      status: 'connected',
      href: '/console/integrations/sardine',
      ...customIngestionSetup,
    },
    {
      id: 'socure',
      name: 'Socure',
      category: 'identity',
      purpose: 'Identity verification and KYC evidence.',
      used_for: ['risk-brd'],
      status: 'degraded',
      href: '/console/integrations/socure',
      ...customIngestionSetup,
    },
  ],
  source_insights: [
    {
      insight_id: 'posthog:behavior-signal',
      source_id: 'posthog',
      source_name: 'PostHog',
      title: 'Behavior signal',
      finding: 'KYC drop-off is concentrated after document upload, where users retry before leaving the flow.',
      evidence: 'Funnel and cohort packets from PostHog show the stall before completion and the recovery path.',
      decision_relevance: 'Prioritize the upload-retry experience before changing upstream onboarding copy.',
      gap: null,
      metric: '11 point conversion drop, 3 retry events per stalled user',
      updated_at: now,
      topic_ids: ['kyc-conversion', 'onboarding'],
      owner: 'Product Analytics',
      quality: {
        score: 1,
        checks: {
          has_clear_finding: true,
          has_evidence: true,
          has_metric_or_observed_change: true,
          has_decision_relevance: true,
          has_owner_or_topic: true,
          has_freshness_timestamp: true,
          declares_gap_when_not_fresh: true,
          passes_redaction_policy: true,
        },
        blockers: [],
      },
      href: '/console/integrations/posthog',
      source_status: 'connected',
      method: 'custom_ingestion',
      source_url: '/console/integrations/posthog',
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
    {
      insight_id: 'metabase:kpi-movement',
      source_id: 'metabase',
      source_name: 'Metabase',
      title: 'KPI movement',
      finding: 'Funding-start rate is steady, but completion is underperforming for returning users.',
      evidence: 'Metabase KPI packets compare current funnel movement against the previous 30-day baseline.',
      decision_relevance: 'Aim engineering review at the completion step instead of the acquisition path.',
      gap: null,
      metric: '7 percent completion decline, flat start volume',
      updated_at: '2026-04-21T13:20:00Z',
      topic_ids: ['funding'],
      owner: 'Data',
      quality: {
        score: 1,
        checks: {
          has_clear_finding: true,
          has_evidence: true,
          has_metric_or_observed_change: true,
          has_decision_relevance: true,
          has_owner_or_topic: true,
          has_freshness_timestamp: true,
          declares_gap_when_not_fresh: true,
          passes_redaction_policy: true,
        },
        blockers: [],
      },
      href: '/console/integrations/metabase',
      source_status: 'connected',
      method: 'custom_ingestion',
      source_url: '/console/integrations/metabase',
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
    {
      insight_id: 'socure:identity-verification',
      source_id: 'socure',
      source_name: 'Socure',
      title: 'Identity verification',
      finding: 'Retry policy review is important, but current identity evidence needs freshness validation.',
      evidence: 'Socure packets should include decisions, retry outcomes, and policy reason codes.',
      decision_relevance: 'Do not ship a policy recommendation until the source bridge proves recent verification outcomes.',
      gap: 'Freshness validation is lagging for Socure evidence.',
      metric: 'approval rate, retry rate, and decline reason mix',
      updated_at: null,
      topic_ids: ['kyc-conversion'],
      owner: 'Risk',
      quality: {
        score: 0.875,
        checks: {
          has_clear_finding: true,
          has_evidence: true,
          has_metric_or_observed_change: true,
          has_decision_relevance: true,
          has_owner_or_topic: true,
          has_freshness_timestamp: false,
          declares_gap_when_not_fresh: true,
          passes_redaction_policy: true,
        },
        blockers: ['has_freshness_timestamp'],
      },
      href: '/console/integrations/socure',
      source_status: 'degraded',
      method: 'custom_ingestion',
      source_url: '/console/integrations/socure',
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
  ],
  source_packets: [
    {
      packet_id: 'demo:posthog',
      source_id: 'posthog',
      source_name: 'PostHog',
      title: 'Demo KYC upload funnel',
      snippet: 'Mobile users recover after the first upload retry, then drop sharply when the second retry fails without a clear next step.',
      metric: '11 point drop after second retry',
      source_url: '/console/integrations/posthog',
      doc_updated_at: now,
      persisted_at: null,
      last_seen_at: null,
      last_ingested_at: null,
      connector_document_id: null,
      sync_run_id: null,
      onyx_document_id: null,
      external_id: 'demo-posthog',
      topic_ids: ['kyc-conversion', 'onboarding'],
      owner: 'Product Analytics',
      product_area: 'onboarding',
      sensitivity: 'internal',
      redaction_profile: 'summary',
      status: 'demo',
      source_status: 'connected',
      method: 'custom_ingestion',
      stale: false,
      changed_since_last_sync: false,
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
    {
      packet_id: 'demo:metabase',
      source_id: 'metabase',
      source_name: 'Metabase',
      title: 'Demo funding funnel dashboard',
      snippet: 'Funding-start volume is flat, but completion fell 7 percent for returning users over the latest 30-day window.',
      metric: '7 percent completion decline',
      source_url: '/console/integrations/metabase',
      doc_updated_at: '2026-04-21T13:20:00Z',
      persisted_at: null,
      last_seen_at: null,
      last_ingested_at: null,
      connector_document_id: null,
      sync_run_id: null,
      onyx_document_id: null,
      external_id: 'demo-metabase',
      topic_ids: ['funding'],
      owner: 'Data',
      product_area: 'funding',
      sensitivity: 'internal',
      redaction_profile: 'summary',
      status: 'demo',
      source_status: 'connected',
      method: 'custom_ingestion',
      stale: false,
      changed_since_last_sync: false,
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
    {
      packet_id: 'demo:dragonboat',
      source_id: 'dragonboat',
      source_name: 'Dragonboat',
      title: 'Demo roadmap commitment packet',
      snippet: 'Funding completion remains committed for the quarter, but the dependency on payment-retry diagnostics moved one sprint.',
      metric: '1 committed initiative, 1 date movement',
      source_url: '/console/integrations/dragonboat',
      doc_updated_at: '2026-04-21T12:45:00Z',
      persisted_at: null,
      last_seen_at: null,
      last_ingested_at: null,
      connector_document_id: null,
      sync_run_id: null,
      onyx_document_id: null,
      external_id: 'demo-dragonboat',
      topic_ids: ['funding'],
      owner: 'Product Ops',
      product_area: 'funding',
      sensitivity: 'internal',
      redaction_profile: 'summary',
      status: 'demo',
      source_status: 'connected',
      method: 'custom_ingestion',
      stale: false,
      changed_since_last_sync: false,
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
    {
      packet_id: 'demo:socure',
      source_id: 'socure',
      source_name: 'Socure',
      title: 'Demo identity retry packet',
      snippet: 'Identity approval is steady overall, while retry volume is concentrated in address mismatch reason codes.',
      metric: 'retry volume concentrated in address mismatch',
      source_url: '/console/integrations/socure',
      doc_updated_at: '2026-04-20T15:10:00Z',
      persisted_at: null,
      last_seen_at: null,
      last_ingested_at: null,
      connector_document_id: null,
      sync_run_id: null,
      onyx_document_id: null,
      external_id: 'demo-socure',
      topic_ids: ['kyc-conversion'],
      owner: 'Risk',
      product_area: 'identity',
      sensitivity: 'internal',
      redaction_profile: 'summary',
      status: 'demo',
      source_status: 'degraded',
      method: 'custom_ingestion',
      stale: false,
      changed_since_last_sync: false,
      is_demo: true,
      provenance: {
        kind: 'demo_packet',
        connector_document_id: null,
        sync_run_id: null,
        output_id: null,
      },
    },
  ],
  source_contradictions: [
    {
      contradiction_id: 'funding:demo-dragonboat:demo-metabase',
      topic_id: 'funding',
      title: 'Funding evidence points in different directions',
      summary: 'Dragonboat shows the initiative is still committed, while Metabase shows completion is declining.',
      severity: 'warning',
      source_ids: ['dragonboat', 'metabase'],
      packet_ids: ['demo:dragonboat', 'demo:metabase'],
      evidence: [
        'Funding completion remains committed for the quarter.',
        'Funding completion fell 7 percent for returning users.',
      ],
      recommended_action: 'Check whether the roadmap commitment reflects the latest funnel movement before recommending scope.',
      updated_at: '2026-04-21T13:20:00Z',
      is_demo: true,
    },
  ],
  source_refresh: {
    configured: false,
    schedule_id: null,
    cadence_days: null,
    next_run_at: null,
    last_run_at: null,
    active_source_count: 9,
    packet_count: 0,
    demo_packet_count: 4,
    failed_source_count: 0,
    stale_source_count: 0,
    latest_sync_status: null,
    latest_sync_at: null,
    href: '/api/console/source-refresh/schedule',
  },
  evidence_export_summary: {
    href: '/api/console/evidence-export',
    generated_at: now,
    source_packet_count: 4,
    real_source_packet_count: 0,
    demo_source_packet_count: 4,
    contradiction_count: 1,
    refresh_configured: false,
    contains_demo_data: true,
  },
  custom_topics: [],
  domain_health: [
    {
      domain: 'planning',
      trust_score: 0.91,
      pass_rate: 0.89,
      issue_count: 0,
    },
    {
      domain: 'metrics',
      trust_score: 0.86,
      pass_rate: 0.84,
      issue_count: 1,
    },
    {
      domain: 'generation',
      trust_score: 0.88,
      pass_rate: 0.87,
      issue_count: 1,
    },
    {
      domain: 'publish',
      trust_score: 0.9,
      pass_rate: 0.8,
      issue_count: 0,
    },
  ],
}

export function shouldUseDevelopmentSlice(): boolean {
  return import.meta.env.DEV && import.meta.env.VITE_USE_API !== 'true'
}

export function shouldForceDevelopmentSlice(): boolean {
  if (!import.meta.env.DEV || typeof window === 'undefined') {
    return false
  }
  return new URLSearchParams(window.location.search).get('demo') === '1'
}
